---
datacenter:
  children:
    routers:
      hosts:
        device IP
      vars:
        testVar: 999
    switches:
      hosts:
        device IP
  vars:
    ansible_connection: network_cli
    ansible_network_os: ce
    ansible_user: ansible
    ansible_ssh_pass: senha@123
    ansible_become_password: senha@123
    ntp_server:
      - device IP
